"""
Response schemas for the AI Agent.

This module defines the structure for responses from the AI agent.
"""
from typing import List, Dict, Any, Optional, Union, AsyncIterator
from enum import Enum
from pydantic import BaseModel, Field


class MessageRole(str, Enum):
    """Enum for possible message roles."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    FUNCTION = "function"
    TOOL = "tool"


class AgentMessage(BaseModel):
    """A message in the conversation with the agent."""
    role: MessageRole = Field(..., description="The role of the message sender")
    content: str = Field(..., description="The content of the message")
    
    class Config:
        frozen = True


class AgentResponse(BaseModel):
    """Response from the AI Agent."""
    messages: List[AgentMessage] = Field(
        default_factory=list,
        description="The messages generated by the agent"
    )
    error: Optional[str] = Field(
        None, 
        description="Error message if something went wrong during processing"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata about the response"
    )
    
    @property
    def content(self) -> str:
        """Get the content of the last assistant message."""
        for message in reversed(self.messages):
            if message.role == MessageRole.ASSISTANT:
                return message.content
        return ""


# Type definition for the streaming response
AgentStreamResponse = AsyncIterator[AgentMessage] 